// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by design/interface/regmap.py -- do not edit by hand.
// `python3 design/interface/regmap.py --check` fails if this file and the register
// map disagree; regenerate with `python3 design/interface/regmap.py`.
//
// The map itself is fixed by
// spec/decision-records/DR-0013-interface-register-map-and-streaming-semantics.md.

`ifndef TRNG_REGMAP_VH
`define TRNG_REGMAP_VH

localparam integer TRNG_REG_BITS   = 32;
localparam integer TRNG_ADDR_W     = 2;
localparam integer TRNG_LEVEL_BITS = 4;
localparam integer TRNG_RAW_PACK_BITS = 32;

// Register addresses (word index; byte offset = index * 4).
localparam [TRNG_ADDR_W-1:0] TRNG_ADDR_CTRL = 2'd0;
localparam [TRNG_ADDR_W-1:0] TRNG_ADDR_STATUS = 2'd1;
localparam [TRNG_ADDR_W-1:0] TRNG_ADDR_DATA = 2'd2;
localparam [TRNG_ADDR_W-1:0] TRNG_ADDR_RAW_DATA = 2'd3;

// CTRL fields.
localparam integer TRNG_CTRL_EN_BIT = 0;
localparam integer TRNG_CTRL_OUT_MODE_BIT = 1;
localparam integer TRNG_CTRL_SOFT_RESET_BIT = 2;
localparam [TRNG_REG_BITS-1:0] TRNG_CTRL_RESET = 32'h00000001;

// STATUS fields.
localparam integer TRNG_STATUS_HT_FAIL_RCT_BIT = 0;
localparam integer TRNG_STATUS_HT_FAIL_APT_BIT = 1;
localparam integer TRNG_STATUS_HT_ALARM_BIT = 2;
localparam integer TRNG_STATUS_STARTUP_BIT = 3;
localparam integer TRNG_STATUS_COND_READY_BIT = 4;
localparam integer TRNG_STATUS_DATA_AVAIL_BIT = 5;
localparam integer TRNG_STATUS_RAW_AVAIL_BIT = 6;
localparam integer TRNG_STATUS_OVF_DATA_BIT = 7;
localparam integer TRNG_STATUS_OVF_RAW_BIT = 8;
localparam integer TRNG_STATUS_HT_FAIL_RING_BIT = 9;
localparam integer TRNG_STATUS_DATA_LEVEL_LSB = 16;
localparam integer TRNG_STATUS_DATA_LEVEL_MSB = 19;
localparam integer TRNG_STATUS_RAW_LEVEL_LSB = 20;
localparam integer TRNG_STATUS_RAW_LEVEL_MSB = 23;
localparam [TRNG_REG_BITS-1:0] TRNG_STATUS_RESET = 32'h00000008;

`endif  // TRNG_REGMAP_VH
