#!/usr/bin/env python3
"""Generate ring1's well-tied extracted netlist and its testbench (issue #339).

    python3 sim/tb/ro-ring11-pex-welltied/build_welltied.py           # write both files
    python3 sim/tb/ro-ring11-pex-welltied/build_welltied.py --check   # fail if either is stale

Why
---
The drawn layout has no n-well ties, so `klt extract` leaves every PMOS body
on an anonymous, floating well net, and `klt pex` reports the committed
envelope's `body_bias.status` as "unbiased" (23 of 23 devices, 11 wells).
signoff/evidence/post-layout/ro_ring11.extracted.spice is therefore a netlist
`klt` itself calls physically wrong to re-simulate. This script builds the
counterfactual in which each of those bodies is tied to `vddr`, which is what
the schematic does, so the two can be compared at every corner.

What it does
------------
Reads the envelope's `body_bias.unbiased_pmos_body_nets` (the list of
{device, net} pairs `klt pex` reported) and, in a copy of the extracted
netlist, rewrites the 4th terminal (body) of each listed `X<device>` card from
its anonymous well net to `vddr`. Nothing else in the netlist changes. The
rewiring is derived from the envelope, never hand-edited, and it raises
rather than guess when:

  * a listed device has no card, or more than one;
  * the card is not a `pfet_*` card, or its body is not the net the envelope
    names;
  * the number of rewired cards is not exactly `unbiased_device_count`, or the
    set of distinct wells rewired is not the envelope's `unbiased_nets`;
  * any pfet card in the netlist is not covered by the envelope (a PMOS the
    envelope does not call unbiased is left alone only if it already sits on
    a named supply net);
  * an old well net is still referenced anywhere after the rewrite.

The body goes to the `vddr` port node itself, not to a parasitic hub of it
(`vddr__tN`), i.e. through no series resistance. That is the idealised tie the
schematic has; a drawn tie would add some access resistance, so this is the
best case for the tie.

`tb_ro_ring11_pex_welltied.sp` is the `ro-ring11-pex` testbench byte for byte
except for its header comment and its one `.include` line, which is replaced
by the well-tied netlist's own text. The batch backend of klt 0.6.0 uploads the
testbench file alone, not the files it `.include`s (the fleet job fails with
"Could not find include file"), so the deck has to be self-contained for the
27-corner grid to run there. `--check` holds the inlined text to the netlist
file, which stays the artefact the records cite.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]
ENVELOPE = REPO_ROOT / "signoff/evidence/post-layout/ro_ring11.pex.json"
SOURCE_NETLIST = REPO_ROOT / "signoff/evidence/post-layout/ro_ring11.extracted.spice"
SOURCE_TB = REPO_ROOT / "sim/tb/ro-ring11-pex/tb_ro_ring11_pex.sp"
OUT_NETLIST = HERE / "ro_ring11.welltied.extracted.spice"
OUT_TB = HERE / "tb_ro_ring11_pex_welltied.sp"
TIE_NET = "vddr"
SOURCE_INCLUDE = '.include "ro_ring11_schematic.spice"'

HEADER = (
    "* WELL-TIED COUNTERFACTUAL -- GENERATED by sim/tb/ro-ring11-pex-welltied/build_welltied.py\n"
    "* from signoff/evidence/post-layout/ro_ring11.extracted.spice and the\n"
    "* body_bias block of ro_ring11.pex.json (issue #339). Do not edit by hand.\n"
    "* The only change from the source netlist: the body (4th terminal) of every PMOS\n"
    "* the envelope lists as unbiased is rewired from its floating well net to 'vddr'.\n"
    "* The layout draws no n-well tie; this netlist is NOT a drawn-layout result.\n"
)


class BuildError(Exception):
    pass


def _cards(text: str) -> list[list[str]]:
    """Group physical lines into logical cards: list of [first_line_index, ...]."""
    out: list[list[str]] = []
    for i, line in enumerate(text.splitlines()):
        if line.startswith("+") and out:
            out[-1].append(i)
        else:
            out.append([i])
    return out


def rewire(netlist: str, body_bias: dict) -> tuple[str, int]:
    """Return (rewired netlist text, rewired card count)."""
    if body_bias.get("status") != "unbiased":
        raise BuildError(f"envelope body_bias.status is {body_bias.get('status')!r}, expected 'unbiased'")
    pairs = body_bias["unbiased_pmos_body_nets"]
    want_count = body_bias["unbiased_device_count"]
    if len(pairs) != want_count:
        raise BuildError(f"envelope lists {len(pairs)} devices but unbiased_device_count is {want_count}")
    target = {p["device"]: p["net"] for p in pairs}
    if len(target) != len(pairs):
        raise BuildError("envelope lists a device twice")

    lines = netlist.splitlines()
    seen: dict[str, int] = {}
    for card in _cards(netlist):
        i = card[0]
        toks = lines[i].split()
        if not toks or toks[0][0] not in "Xx" or len(toks) < 6:
            continue
        dev = toks[0][1:]
        model = toks[5].lower()
        if model.startswith("pfet") and dev not in target:
            raise BuildError(f"pfet card {toks[0]} is not in the envelope's unbiased list")
        if dev not in target:
            continue
        if not model.startswith("pfet"):
            raise BuildError(f"{toks[0]} is listed as a PMOS but its model is {toks[5]!r}")
        if toks[4] != target[dev]:
            raise BuildError(f"{toks[0]} body is {toks[4]!r}, envelope says {target[dev]!r}")
        if seen.get(dev):
            raise BuildError(f"device {dev} has more than one card")
        seen[dev] = 1
        toks[4] = TIE_NET
        lines[i] = " ".join(toks)

    missing = sorted(set(target) - set(seen))
    if missing:
        raise BuildError(f"envelope devices with no card in the netlist: {missing}")
    if len(seen) != want_count:
        raise BuildError(f"rewired {len(seen)} cards, expected {want_count}")
    wells = set(target.values())
    if wells != set(body_bias["unbiased_nets"]):
        raise BuildError(f"rewired wells {sorted(wells)} != envelope unbiased_nets")

    out = "\n".join(lines) + "\n"
    for well in wells:
        if re.search(rf"(?<![\w$|\\]){re.escape(well)}(?![\w$|])", out):
            raise BuildError(f"well net {well} is still referenced after the rewrite")
    return out, len(seen)


def render() -> tuple[str, str]:
    body_bias = json.loads(ENVELOPE.read_text())["body_bias"]
    netlist, _n = rewire(SOURCE_NETLIST.read_text(), body_bias)
    tb = SOURCE_TB.read_text()
    if tb.count(SOURCE_INCLUDE) != 1:
        raise BuildError(f"{SOURCE_TB.name}: expected exactly one {SOURCE_INCLUDE!r}")
    full = HEADER + netlist
    tb = tb.replace(SOURCE_INCLUDE, "* ---- begin inlined ro_ring11.welltied.extracted.spice ----\n" + full
                    + "* ---- end inlined ro_ring11.welltied.extracted.spice ----")
    tb = (
        "* GENERATED by sim/tb/ro-ring11-pex-welltied/build_welltied.py from\n"
        "* sim/tb/ro-ring11-pex/tb_ro_ring11_pex.sp: identical except that the .include of the\n"
        "* schematic DUT is replaced by the text of ro_ring11.welltied.extracted.spice, so the\n"
        "* deck is self-contained for the batch backend (issue #339). Do not edit by hand.\n"
        + tb
    )
    return full, tb


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    try:
        netlist, tb = render()
        pairs = ((OUT_NETLIST, netlist), (OUT_TB, tb))
        if args.check:
            for path, want in pairs:
                if not path.is_file() or path.read_text() != want:
                    raise BuildError(f"{path.relative_to(REPO_ROOT)} is stale; re-run build_welltied.py")
            print("build_welltied: well-tied netlist and testbench are current (23 of 23 bodies tied)")
            return 0
        for path, want in pairs:
            path.write_text(want)
            print(f"build_welltied: wrote {path.relative_to(REPO_ROOT)}")
        return 0
    except (BuildError, KeyError, json.JSONDecodeError) as exc:
        print(f"build_welltied: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
