#!/usr/bin/env python3
"""Re-derive `sim/characterization-digital-activity-power.md` from its records
(#453) and gate the trace-dependent evidence behind it.

    python3 sim/tools/activity_power_characterization.py            # report
    python3 sim/tools/activity_power_characterization.py --markdown # the generated tables
    python3 sim/tools/activity_power_characterization.py --check    # gate (no PDK, no simulator)

The records are `sim/records/*-digital-sta-activity-<nn>.md` (one per corner
of the 15-point liberty x interconnect matrix, minted by
`run_sta.py --activity`). `--check` fails unless:

- a complete 15-corner family exists whose `netlist.sha` equals the committed
  `layout/digital/trng_top.def` blob and whose pinned `pnr.v` blob equals the
  committed `layout/digital/trng_top.pnr.v`;
- all 15 records pin the same trace identities (VCD and stimulus sha256,
  windows, seeds), and each stimulus hash equals what
  `activity_workloads.py` generates today (a changed workload makes the
  records stale, not silently wrong);
- each record pins the current gate-simulation testbench blob (strict:
  any edit to `activity_tb.v` stales the capture), and its committed raw
  `activity-manifest.json` (checksummed in the record) agrees with the
  record and, per workload, with what the capture program generates today:
  stimulus, cycle count, clock period, seeds and capture-window boundaries
  (semantic: the workloads module is not compared by blob, so a comment-only
  edit is harmless but a window-only change is not);
- the workload set equals the declared default campaign
  (`activity_workloads.WORKLOADS`) in every record, with missing, extra and
  duplicate workloads named. Diagnostic subset captures stay possible but
  are not accepted as the published aggregate;
- every record's uniform baseline equals the default flow's
  `digital-sta-power` 1 MHz total at the same corner and DEF (like-for-like
  by construction, re-verified);
- every (workload, window) in every record was annotated with no
  unannotated pins above the declared tolerance;
- the companion document contains exactly the tables this tool generates
  between its markers.

It never edits the ratified rollup baseline: the whole-block comparison it
prints is an illustrative substitution, labelled as such.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

SIM_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = SIM_DIR.parent
sys.path.insert(0, str(SIM_DIR / "tools"))
sys.path.insert(0, str(SIM_DIR / "tb" / "trng-top-post-route"))
sys.path.insert(0, str(SIM_DIR / "tb" / "digital-sta-power"))

from _record_parsing import parse_values  # noqa: E402

import hashlib  # noqa: E402

RECORDS = SIM_DIR / "records"
DOC = SIM_DIR / "characterization-digital-activity-power.md"
BEGIN = "<!-- activity-tables:begin (generated by sim/tools/activity_power_characterization.py; do not edit) -->"
END = "<!-- activity-tables:end -->"
LIBERTY = ("ss_125C_3v00", "ss_n40C_3v00", "tt_025C_3v30", "ff_125C_3v60", "ff_n40C_3v60")
RCS = ("min", "nom", "max")
EXPECTED = tuple(f"{l}/rc-{r}" for l in LIBERTY for r in RCS)
WINDOWS = ("reset", "startup", "steady")
#: A record's windows may leave at most this many pins unannotated (reported
#: either way).
MAX_UNANNOTATED_FRACTION = 0.01


class CheckError(RuntimeError):
    pass


def blob_sha(path: Path) -> str:
    data = path.read_bytes()
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


class Rec:
    def __init__(self, path: Path):
        text = path.read_text()
        self.path, self.stem = path, path.stem
        fm = re.match(r"---\n(.*?)\n---\n", text, re.S)
        if not fm:
            raise CheckError(f"{self.stem}: no frontmatter")
        self.fm = fm.group(1)
        self.status = self._one(r"^status:\s*(\S+)")
        self.liberty = self._one(r"^\s+liberty:\s*\S+__(\S+)")
        self.rc = self._one(r"^\s+interconnect:\s*(\S+)")
        self.vdd = float(self._one(r"^\s+voltage:\s*([\d.]+)"))
        self.def_sha = self._one(r"^netlist:\s*\n\s+path:.*\n\s+sha:\s*([0-9a-f]+)")
        self.pnr_sha = self._one(r"netlist layout/digital/trng_top\.pnr\.v \(sha ([0-9a-f]+)\)")
        self.traces = re.findall(
            r"- workload: (\S+)\n\s+vcd_sha256: (\w+)\n\s+vcd_bytes: (\d+)\n\s+stimulus_sha256: (\w+)\n"
            r"\s+cycles: (\d+)\n\s+windows_cycles: (\{.*\})\n", self.fm)
        self.testbench_sha = self._one(r"^\s+testbench_sha:\s*([0-9a-f]{40})\s*$")
        self.raw_path = self._one(r"^raw:\s*\n\s+path:\s*(\S+)")
        self.manifest_sha = self._one(r"^\s+- activity-manifest\.json\s+sha256:([0-9a-f]{64})")
        self._manifest = None
        self.seeds = self._one(r"^seeds:\s*(.*)$")
        self.values = parse_values(text, label=self.stem, error_cls=CheckError)
        self.corner = f"{self.liberty}/rc-{self.rc}"

    def _one(self, pat: str) -> str:
        m = re.search(pat, self.fm, re.M)
        if not m:
            raise CheckError(f"{self.stem}: cannot find /{pat}/ in the frontmatter")
        return m.group(1)

    def manifest(self) -> dict:
        """The committed raw activity manifest, checksummed against the record."""
        if self._manifest is None:
            path = REPO_ROOT / self.raw_path / "activity-manifest.json"
            if not path.is_file():
                raise CheckError(f"{self.stem}: raw manifest {path.relative_to(REPO_ROOT)} is missing")
            if hashlib.sha256(path.read_bytes()).hexdigest() != self.manifest_sha:
                raise CheckError(f"{self.stem}: raw manifest does not match its recorded sha256")
            self._manifest = json.loads(path.read_text())
        return self._manifest

    def v(self, key: str) -> float:
        if key not in self.values:
            raise CheckError(f"{self.stem}: no `{key}`")
        return self.values[key]


def load_family() -> dict[str, Rec]:
    recs = [Rec(p) for p in sorted(RECORDS.glob("*-digital-sta-activity-[0-9]*.md"))]
    recs = [r for r in recs if r.status == "valid"]
    cur_def = blob_sha(REPO_ROOT / "layout/digital/trng_top.def")
    cur_pnr = blob_sha(REPO_ROOT / "layout/digital/trng_top.pnr.v")
    fam: dict[str, Rec] = {}
    stale = []
    for r in recs:
        if r.def_sha != cur_def or r.pnr_sha != cur_pnr:
            stale.append(r.stem)
            continue
        fam[r.corner] = r  # sorted by stem: the latest valid record wins
    missing = [c for c in EXPECTED if c not in fam]
    if missing:
        raise CheckError(
            f"no complete current-netlist family: missing {missing}"
            + (f"; {len(stale)} record(s) describe an earlier DEF/netlist" if stale else "")
        )
    return fam


def workloads(fam: dict[str, Rec]) -> list[str]:
    names = sorted({t[0] for r in fam.values() for t in r.traces})
    return names


def key(workload: str, window: str, term: str) -> str:
    return f"obs_{workload.replace('-', '_')}_{window}_{term}"


def campaign_problems(r: Rec, expected: tuple[str, ...]) -> list[str]:
    """Missing / extra / duplicate workloads in one record's trace list."""
    names = [t[0] for t in r.traces]
    out = [f"{r.stem}: duplicate workload trace {n}" for n in sorted({n for n in names if names.count(n) > 1})]
    missing = [n for n in expected if n not in names]
    extra = sorted(set(names) - set(expected))
    if missing:
        out.append(f"{r.stem}: incomplete campaign, missing workload(s) {missing}")
    if extra:
        out.append(f"{r.stem}: undeclared workload(s) {extra} not in the default campaign")
    return out


def capture_source_problems(r: Rec) -> list[str]:
    """Freshness of the capture program behind one record (no VCD/PDK needed)."""
    import activity as act  # noqa: PLC0415

    out: list[str] = []
    cur_tb = blob_sha(act.TB_SOURCE)
    if r.testbench_sha != cur_tb:
        out.append(f"{r.stem}: stale capture testbench: record pins {r.testbench_sha}, "
                   f"{act.TB_SOURCE.name} is now {cur_tb}")
    try:
        m = r.manifest()
        act.verify_capture_source(m, f"{r.stem} raw manifest")
    except (CheckError, act.ActivityError, KeyError, ValueError) as exc:
        return out + [str(exc)]
    if m["identities"]["testbench"]["git_blob_sha"] != r.testbench_sha:
        out.append(f"{r.stem}: record testbench_sha differs from its raw manifest")
    by_name = {}
    for n, t in m["traces"].items():
        by_name[n] = t
    if sorted(by_name) != sorted(t[0] for t in r.traces):
        out.append(f"{r.stem}: record traces {sorted(t[0] for t in r.traces)} differ from raw manifest "
                   f"traces {sorted(by_name)}")
    for name, vcd, size, stim, cycles, win in r.traces:
        t = by_name.get(name)
        if t is None:
            continue
        try:
            same = (t["vcd_sha256"] == vcd and str(t["vcd_bytes"]) == size
                    and t["stimulus_sha256"] == stim and str(t["cycles"]) == cycles
                    and json.loads(win) == t["windows_cycles"])
        except (KeyError, ValueError):
            same = False
        if not same:
            out.append(f"{r.stem}: trace {name} in the record differs from its raw manifest")
    return out


def check(fam: dict[str, Rec], expected: tuple[str, ...] | None = None) -> list[str]:
    problems: list[str] = []
    import activity_workloads as wl  # noqa: PLC0415

    expected = tuple(wl.WORKLOADS) if expected is None else expected
    for r in fam.values():
        problems += campaign_problems(r, expected)
        problems += capture_source_problems(r)

    first = next(iter(fam.values()))
    for c, r in fam.items():
        if r.traces != first.traces or r.seeds != first.seeds:
            problems.append(f"{r.stem}: trace identities differ from {first.stem}")
    if not first.traces:
        problems.append("records pin no traces")
    for name, _vcd, _bytes, stim, cycles, _win in first.traces:
        if name not in wl.WORKLOADS:
            problems.append(f"workload {name} no longer exists")
            continue
        rows, _ = wl.build(name)
        if wl.stimulus_sha256(rows) != stim or len(rows) != int(cycles):
            problems.append(f"workload {name}: records are stale (stimulus changed)")
    # Like-for-like re-verification against the default flow's records.
    default = {}
    for p in sorted(RECORDS.glob("*-digital-sta-power-[0-9]*.md")):
        t = p.read_text()
        if "status: valid" not in t.split("\n---")[0]:
            continue
        m = re.search(r"^netlist:\s*\n\s+path:.*\n\s+sha:\s*([0-9a-f]+)", t, re.M)
        lib = re.search(r"^\s+liberty:\s*\S+__(\S+)", t, re.M)
        rc = re.search(r"^\s+interconnect:\s*(\S+)", t, re.M)
        if m and lib and rc and m.group(1) == first.def_sha:
            default[f"{lib.group(1)}/rc-{rc.group(1)}"] = parse_values(t, label=p.stem, error_cls=CheckError)
    for c, r in fam.items():
        base = default.get(c)
        if base is None:
            problems.append(f"{c}: no default-flow record for the same DEF to compare against")
            continue
        a, b = r.v("uniform_total_w"), base["p_total_1mhz_w"]
        if abs(a - b) > 1e-6 * b:
            problems.append(f"{c}: uniform baseline {a:.6e} != default flow {b:.6e}")
    for c, r in fam.items():
        for name in [n for n in workloads(fam) if n in expected]:
            for w in WINDOWS:
                ann = r.v(key(name, w, "annotated_pins"))
                un = r.v(key(name, w, "unannotated_pins"))
                if ann <= 0 or un / (ann + un) > MAX_UNANNOTATED_FRACTION:
                    problems.append(f"{c} {name}/{w}: {int(un)} of {int(ann + un)} pins unannotated")
                parts = sum(r.v(key(name, w, t)) for t in ("internal_w", "switching_w", "leakage_w"))
                if abs(parts - r.v(key(name, w, "total_w"))) > 1e-5 * parts:
                    problems.append(f"{c} {name}/{w}: terms do not sum to the total")
    return problems


def markdown(fam: dict[str, Rec]) -> str:
    names = workloads(fam)
    out: list[str] = []
    a = out.append
    a("### Same netlist, same rate: uniform vs observed, steady window, every corner")
    a("")
    a("Digital total power in uW at 1 MHz (`report_power`), identical SPEF in both columns.")
    a("")
    a("| corner | uniform 0.25 | " + " | ".join(names) + " | observed max / uniform |")
    a("|---|---:|" + "---:|" * len(names) + "---:|")
    for c in EXPECTED:
        r = fam[c]
        u = r.v("uniform_total_w")
        vals = [r.v(key(n, "steady", "total_w")) for n in names]
        a(f"| {c} | {u * 1e6:.2f} | " + " | ".join(f"{v * 1e6:.2f}" for v in vals)
          + f" | {max(vals) / u:.3f} |")
    a("")
    a("### Workload-specific maxima over the 15 corners (uW) and where they bind")
    a("")
    a("| workload | window | max total | at corner | internal | switching | leakage | vs uniform at that corner |")
    a("|---|---|---:|---|---:|---:|---:|---:|")
    for n in names:
        for w in WINDOWS:
            c = max(EXPECTED, key=lambda c: fam[c].v(key(n, w, "total_w")))
            r = fam[c]
            a(f"| {n} | {w} | {r.v(key(n, w, 'total_w')) * 1e6:.2f} | {c} | "
              f"{r.v(key(n, w, 'internal_w')) * 1e6:.2f} | {r.v(key(n, w, 'switching_w')) * 1e6:.2f} | "
              f"{r.v(key(n, w, 'leakage_w')) * 1e6:.3f} | {r.v(key(n, w, 'total_w')) / r.v('uniform_total_w'):.3f} |")
    a("")
    a("### Term breakdown at the digital-binding corner of the ratified rollup (ff_125C_3v60/rc-max)")
    a("")
    c = "ff_125C_3v60/rc-max"
    r = fam[c]
    a("| workload / window | clock | sequential | combinational | internal | switching | leakage | total |")
    a("|---|---:|---:|---:|---:|---:|---:|---:|")
    a(f"| uniform | {r.v('uniform_clock_w') * 1e6:.2f} | {r.v('uniform_sequential_w') * 1e6:.2f} | "
      f"{r.v('uniform_combinational_w') * 1e6:.2f} | {r.v('uniform_internal_w') * 1e6:.2f} | "
      f"{r.v('uniform_switching_w') * 1e6:.2f} | {r.v('uniform_leakage_w') * 1e6:.3f} | "
      f"{r.v('uniform_total_w') * 1e6:.2f} |")
    for n in names:
        for w in WINDOWS:
            k = lambda t: r.v(key(n, w, t)) * 1e6  # noqa: E731
            a(f"| {n} / {w} | {k('clock_w'):.2f} | {k('sequential_w'):.2f} | {k('combinational_w'):.2f} | "
              f"{k('internal_w'):.2f} | {k('switching_w'):.2f} | {k('leakage_w'):.3f} | {k('total_w'):.2f} |")
    a("")
    a("### Annotation coverage")
    a("")
    worst_un = max(r.v(key(n, w, "unannotated_pins")) for r in fam.values() for n in names for w in WINDOWS)
    pins = {int(r.v(key(n, w, "annotated_pins") ) + r.v(key(n, w, "unannotated_pins")))
            for r in fam.values() for n in names for w in WINDOWS}
    a(f"Pins in the design as OpenSTA sees them: {sorted(pins)}. Largest unannotated count in any "
      f"(corner, workload, window): {int(worst_un)}. Every window is annotated from the VCD; "
      "no pin runs on a fallback activity in any record.")
    a("")
    a("### Illustration only: whole-block active power if the digital term were the observed maximum")
    a("")
    a("The ratified rollup (`python3 sim/tools/power_rollup.py`) is unchanged and still uses the "
      "uniform-activity digital term. Substituting, at the same digital-binding corner, the largest "
      "observed steady-window total of any declared workload for that term:")
    a("")
    uni = fam[c].v("uniform_total_w")
    obs = max(fam[c].v(key(n, "steady", "total_w")) for n in names)
    a(f"- ratified digital term (uniform, {c}): {uni * 1e6:.1f} uW")
    a(f"- largest observed steady total at the same corner: {obs * 1e6:.1f} uW "
      f"({obs / uni:.3f} of the ratified term)")
    a(f"- change to the whole-block active total at any analog corner: {(obs - uni) * 1e6:+.1f} uW")
    return "\n".join(out)


def run_check(fam: dict[str, Rec]) -> int:
    problems = check(fam)
    if DOC.is_file():
        text = DOC.read_text()
        if BEGIN not in text or END not in text:
            problems.append(f"{DOC.name}: generated-table markers missing")
        else:
            body = text.split(BEGIN, 1)[1].split(END, 1)[0].strip("\n")
            if body != markdown(fam):
                problems.append(f"{DOC.name}: generated tables are stale; run --markdown and paste between the markers")
    else:
        problems.append(f"{DOC.name} does not exist")
    for p in problems:
        print(f"FAIL  {p}")
    if not problems:
        print(f"activity power characterization: {len(fam)} corners, {len(workloads(fam))} workloads x "
              f"{len(WINDOWS)} windows, trace identities consistent, uniform baseline equals the default "
              "flow, document current -- OK")
    return 1 if problems else 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--markdown", action="store_true")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args(argv)
    try:
        fam = load_family()
    except CheckError as exc:
        print(f"FAIL  {exc}")
        return 1
    if args.check:
        try:
            return run_check(fam)
        except CheckError as exc:
            print(f"FAIL  {exc}")
            return 1
    if args.markdown:
        print(markdown(fam))
    elif args.json:
        print(json.dumps({c: r.values for c, r in fam.items()}, indent=1))
    else:
        print(markdown(fam))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
