#!/usr/bin/env python3
"""Declare the `trng_floorplan` inter-region net list, and generate its
top-level LVS reference netlist from that declaration.

    python3 design/floorplan_netlist.py            # self-check, print summary
    python3 design/floorplan_netlist.py --check     # self-check only (same as no args)
    python3 design/floorplan_netlist.py --write     # ... and (re)write the LVS reference

This is **phase 1** of issue #219's two-phase decomposition: a
Python-checkable *data and rationale* declaration, not yet drawn geometry.
`layout/floorplan/floorplan.py`'s `compose()` places four guarded regions
(`ring1`, `ring2`, `combiner_sampler`, `digital`) into one abstract with an
isolation channel between neighbours, but draws no wiring between them --
every net that has to cross a region boundary for the block to actually
function is undeclared today. This module is where that gets written down,
once, as reviewable data: the input contract phase 2 (a separate follow-up
issue, physical routing + DRC/LVS) routes against, so the two phases can
never independently drift on what the net list is.

**No GDS/DRC/LVS work happens here.** `klt extract --top trng_floorplan`'s
pin count is unaffected by this module alone -- nothing it does touches the
composed GDS. See `layout/floorplan/README.md`, "Planned inter-region
connectivity", for the write-up this module's own data backs.

Why a new module, not `design/netlist.py`
-------------------------------------------
`design/netlist.py` is exclusively an xschem-schematic-to-SPICE exporter
(`design/xschem/*.sch` -> `design/*.spice`; see its own module docstring and
`TOP_CELLS`). There is no `design/xschem/trng_floorplan.sch` -- the
floorplan's own inter-region netlist is not a schematic export, it is a
*layout-composition-level* declaration, the same kind of thing
`layout/digital/lvs.py` builds for `trng_top.lvs_reference.spice` (a
hand-derived, `.SUBCKT`-wrapped reference netlist generated by a Python
script under `layout/`, not xschem). This module follows that pattern one
level up: one composed reference for all four regions together, generated
from data declared here and consumed by `layout/floorplan/floorplan.py`
(which imports this module rather than restating any of it).

What is declared, per net (`INTER_REGION_NETS`)
--------------------------------------------------
- `name` -- the net's own name at the composed `trng_floorplan` level.
- `role` -- one of `control` / `clock` / `reset` / `entropy_tap` /
  `raw_tap` / `liveness_tap` / `supply` / `ground` / `substrate`.
- `chip_pin` -- whether this net is also a top-level `trng_floorplan` pin
  (an actual chip I/O), as opposed to a net that is wholly absorbed between
  two regions and never reaches the outside world.
- `endpoints` -- every `(region_id, region_pin_name)` this net connects,
  using **each region's own already-committed reference pin name**
  (`REGION_REFERENCES`) -- never a name invented here. `validate_inter_
  region_nets()` mechanically checks every one of these against the real
  `.SUBCKT` header of the region's own committed `.spice` file, so a typo or
  a region's own future pin rename is caught, not eyeballed.
- `implicit_regions` -- for the two nets (`vddd`, `vss`) that also reach
  `digital`'s real power delivery network through a mechanism `digital`'s
  own committed reference does not expose as a `.SUBCKT` pin at all (see
  "The `digital` region's supply pins are not `.SUBCKT` pins" below). Not
  mechanically checkable the same way `endpoints` is -- there is no pin to
  check against -- so it is kept in its own field rather than silently
  folded into `endpoints`, where it would look checkable and would not be.
- `spans_regions` -- for `ro1` only: the one net whose physical routing path
  (phase 2's job) is not a single-channel hop between adjacent regions.
- `layer_role` -- a target metal-layer *role* (not yet a GDS layer number),
  tied to which coupling mechanism (`layout/floorplan/README.md`'s
  Mechanism 1/2/3) the route must not defeat.
- `rationale` -- why the net exists and why its endpoints/layer choice are
  what they are, tied to the README.

The four supply branches must never merge before a star point
-----------------------------------------------------------------
**`vddr1`, `vddr2`, `vdd` and `vddd` are four topologically distinct nets,
declared as four separate dict entries below with four separate `name`
fields and four disjoint `endpoints` lists. Do not merge them, ever, no
matter how tempting a shared strap looks during phase 2's routing pass.**
`layout/floorplan/README.md`'s Mechanism 1 (per-ring supply routing, item 2)
and Mechanism 2 (star routing, item 1) both depend on these four branches
carrying no shared series impedance until a not-yet-drawn star point at the
block's own supply pad. `validate_inter_region_nets()` asserts this
mechanically (four distinct names, no two supply nets sharing an endpoint or
a region) so a future edit cannot merge them without this check failing.

The `digital` region's supply pins are not `.SUBCKT` pins
--------------------------------------------------------------
`layout/digital/trng_top.lvs_reference.spice`'s own `.SUBCKT trng_top`
header declares 109 pins (verified directly, at run time, by `reference_
top_pins()` below -- not restated as a constant here; #219's own "~12-pin"
note is a caution about trusting a stale figure instead of re-deriving it,
and this module follows that caution rather than repeating it) -- none of
them `vddd` or `vss`. That is deliberate, not an oversight:
`layout/digital/lvs.py`'s own module docstring ("Neither side promotes a
supply to a *top-level* pin", "`run_extract`'s `--pins` declares the 109
real chip I/O nets and nothing else") and `layout/digital/README.md#power`
both record that `digital`'s real, placed-and-routed power delivery network
is real (its `SPECIALNETS` section names `vddd`/`vss`, and the *DEF's own*
`PINS` section -- the physical layout, not this reference netlist's
`.SUBCKT` header -- carries 111 entries, the same 109 chip I/O plus those 2
supply pins), but the *reference netlist* that standalone digital LVS run
built keeps `vddd`/`vss` off both sides' `.SUBCKT trng_top` interface so the
two interfaces still match each other. This module's own `INTER_REGION_NETS`
declares `vddd`'s and `vss`'s connection into `digital` via `implicit_
regions` rather than `endpoints` for exactly that reason: there is no
`.SUBCKT` pin to name. `generate_lvs_reference()` below therefore cannot
wire either net into `digital`'s own `X`-card (the card only has as many
positions as the reference's own header declares) -- `vddd` is written as a
top-level `trng_floorplan` pin with no real wire beneath it in this
generated file, and `vss` is written wired to `ring1`/`ring2`/
`combiner_sampler` only. Both are flagged in the generated file's own header
comment. Reconciling this (if phase 2 needs to) is that follow-up issue's
problem, not this declaration's.

The substrate net `vsubs` (not in issue #219/#221's own inter-region table)
--------------------------------------------------------------------------------
`ring1`, `ring2` and `combiner_sampler`'s own committed reference netlists
each declare a `vsubs` pin (`layout/rings/ro_ring11/ro_ring11.spice`'s own
header comment: "NMOS bulk is the deck's `vsubs` substrate global" --
`layout/verify.py`'s own `EXPECTATIONS` table explains the same thing from
the extraction side: `klt extract` *synthesizes* this net rather than
resolving it from a real drawn label, which is exactly why `device.body_
unverified` is an expected, not a real, LVS disclosure on every one of those
three regions' own standalone checks). `design/trng_top.spice`'s schematic
has no `vsubs` pin at all -- it is a layout-LVS-reference artifact of the
three `klt gen`/`klt draw`-descended regions' own hand-derived `.spice`
files, not part of the design's own inter-region signal/supply list the
issue's table enumerates. It is declared here anyway, as its own net (not
merged into `vss`, even though the guard rings' own p-substrate taps are
physically tied to each region's `vss` return per README Mechanism 2 -- that
is a DRC/physical statement about drawn geometry, not a schematic-netlist
statement, and this reference stays a textually distinct node the same way
the extraction deck's own synthesized `vsubs` handle stays distinct from a
real `vss` label), purely so `generate_lvs_reference()` below can wire a
complete, well-formed `X`-card for all three regions (their own `.SUBCKT`
headers require a 5th/11th pin no matter what this module declares). `digital`
has no `vsubs` pin (its standard-cell library ties NMOS bulk internally, the
same way it has no separate pin for it in any of its abstracted cell types --
see `layout/digital/trng_top.lvs_reference.spice`'s own per-cell-type
`.SUBCKT` headers, none of which carry one either), so `vsubs` never reaches
`digital` and is not a `trng_floorplan` chip pin.

The `ro1` long-haul route (`spans_regions`)
------------------------------------------------
`ring1.ro -> combiner_sampler.rn1` is the one net in this table whose
physical route (phase 2's job) is not a single-channel hop: the composed row
order is `ring1 | ring2 | combiner_sampler | digital`, so this net's two
endpoints are not adjacent regions -- it has to cross, or route around in
the channel space, `ring2`'s own guarded region. `spans_regions: ["ring2"]`
records that so phase 2 does not have to re-discover it by reading the row
order itself.

The `.lvs_reference.spice` generator
----------------------------------------
`generate_lvs_reference()` writes a hand-derived, `.SUBCKT`-wrapped
composed reference at `layout/floorplan/trng_floorplan.lvs_reference.spice`,
the same documented style `layout/floorplan/floorplan.py`'s own
`RING_LVS_REFERENCE` entries and `layout/digital/lvs.py`'s own
`trng_top.lvs_reference.spice` generation already use. Rather than inlining
each region's own (in `digital`'s case, ~8700-line) reference content a
second time -- which would create exactly the two-copies-that-can-drift
problem this repository otherwise goes out of its way to avoid -- it
`.INCLUDE`s the four already-committed reference files by their own
repo-relative path and instantiates each one's own `.SUBCKT` once. **This
file's own well-formedness (does it parse, does it `klt lvs`-match anything)
is not verified here** -- running `klt lvs` against it is phase 2's job, once
real routed geometry exists to compare it against. What this module verifies
is narrower and immediate: that every endpoint it wires actually names a
real pin on the region it claims to (`validate_inter_region_nets()`).
"""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LAYOUT_DIR = REPO_ROOT / "layout"
FLOORPLAN_DIR = LAYOUT_DIR / "floorplan"

#: Where `generate_lvs_reference()` writes the composed top-level reference.
LVS_REFERENCE_PATH = FLOORPLAN_DIR / "trng_floorplan.lvs_reference.spice"

#: The composed abstract's own top-cell name -- `layout/floorplan/
#: floorplan.py`'s own `compose()` already names its `gen-compose` output
#: `trng_floorplan` (`options.cell_name`); this reference's own top `.SUBCKT`
#: matches it so a future `klt lvs` run (phase 2) can point `reference.top`
#: at the same name `layout.top` already resolves to.
TOP_CELL = "trng_floorplan"

EXIT_OK = 0
EXIT_FAIL = 1


class FloorplanNetlistError(RuntimeError):
    """The declared inter-region net list, or a reference file it points
    at, is not internally consistent."""


# --------------------------------------------------------------------------- #
# Region references -- the four regions' own already-committed LVS reference
# netlists, and the `.SUBCKT` name each one uses.
# --------------------------------------------------------------------------- #
#
# The same four (path, top-cell) pairs `layout/floorplan/floorplan.py`'s own
# `RING_LVS_REFERENCE` already names for its placement-check LVS
# (`check_ring_fit`) -- declared here as the canonical copy, and imported by
# `floorplan.py` rather than restated, so the two can never point at
# different files for the same region id.
REGION_REFERENCES: dict[str, tuple[Path, str]] = {
    "ring1": (LAYOUT_DIR / "rings" / "ro_ring11" / "ro_ring11.spice", "ro_ring11"),
    "ring2": (
        LAYOUT_DIR / "rings" / "ro_ring11_ring2" / "ro_ring11_ring2.spice",
        "ro_ring11_ring2",
    ),
    "combiner_sampler": (
        LAYOUT_DIR / "blocks" / "combiner_sampler" / "combiner_sampler.spice",
        "combiner_sampler",
    ),
    "digital": (
        LAYOUT_DIR / "digital" / "trng_top.lvs_reference.spice",
        "trng_top",
    ),
}

#: The composed region order `floorplan.py`'s own `REGIONS`/`compose()` place
#: left to right -- `ro1`'s `spans_regions` below is meaningful only against
#: this order (see the module docstring's "long-haul route" section).
REGION_ORDER: tuple[str, ...] = ("ring1", "ring2", "combiner_sampler", "digital")

#: `(net name, specialnet name)` pairs `digital`'s own real power delivery
#: network carries that its committed reference `.SUBCKT trng_top` header
#: does not expose as a pin -- see the module docstring's "The `digital`
#: region's supply pins are not `.SUBCKT` pins" section. Any `implicit_
#: regions` entry naming `digital` must use one of these two net names, or
#: `validate_inter_region_nets()` rejects it: this is the *only* documented
#: reason a declared connection is allowed to skip the mechanical
#: `.SUBCKT`-pin check.
DIGITAL_IMPLICIT_SPECIALNETS: tuple[str, ...] = ("vddd", "vss")


# --------------------------------------------------------------------------- #
# The inter-region net list -- the data this module exists to declare.
# --------------------------------------------------------------------------- #
#
# Every net here is a direct transcription of issue #221's own exhaustive
# per-net table (itself derived from `design/trng_top.spice`'s own
# `sampler_core` netlist -- `en1 en2 vddr1 vddr2 vdd vss clk rst_n raw_bit
# raw_valid ring_bit1 ring_bit2` -- plus the four regions' own supply/ground
# pins), with `vsubs` added for well-formedness only (see the module
# docstring). Nothing here is inferred or renamed: every `endpoints` pin
# name is the region's own already-committed `.SUBCKT` pin name, unchanged.
INTER_REGION_NETS: list[dict] = [
    {
        "name": "en1",
        "role": "control",
        "chip_pin": True,
        "endpoints": [("ring1", "en")],
        "layer_role": "metal1",
        "rationale": (
            "Ring enable, chip pin straight to ring1's own `en` pin -- no "
            "fan-out, no other region touches it."
        ),
    },
    {
        "name": "en2",
        "role": "control",
        "chip_pin": True,
        "endpoints": [("ring2", "en")],
        "layer_role": "metal1",
        "rationale": "Ring enable, chip pin straight to ring2's own `en` pin.",
    },
    {
        "name": "ro1",
        "role": "entropy_tap",
        "chip_pin": False,
        "endpoints": [("ring1", "ro"), ("combiner_sampler", "rn1")],
        "spans_regions": ["ring2"],
        "layer_role": "metal2",
        "rationale": (
            "Entropy tap, ring1 -> combiner_sampler. The composed row order "
            "(ring1 | ring2 | combiner_sampler | digital) puts ring2 between "
            "these two endpoints, so this route spans (or skirts, in the "
            "channel space) ring2's own guarded region rather than crossing "
            "one adjacent channel -- the one long-haul route in this table, "
            "see the module docstring. Metal2, not Metal1: Metal1 is where "
            "ring2's own intra-ring signal chain runs (`layout/rings/"
            "ro_ring11/build.py`), and this net must not share that layer "
            "over ring2's own footprint."
        ),
    },
    {
        "name": "ro2",
        "role": "entropy_tap",
        "chip_pin": False,
        "endpoints": [("ring2", "ro"), ("combiner_sampler", "rn2")],
        "layer_role": "metal1",
        "rationale": (
            "Entropy tap, ring2 -> combiner_sampler: a single adjacent-"
            "channel hop, so it stays on Metal1, ring1/ring2/combiner_"
            "sampler's own native signal layer -- no other region's signal "
            "metal to avoid."
        ),
    },
    {
        "name": "clk",
        "role": "clock",
        "chip_pin": True,
        "endpoints": [("digital", "clk"), ("combiner_sampler", "clk")],
        "layer_role": "metal4_transition",
        "rationale": (
            "DR-0012's fixed external sample clock -- Mechanism 1's worst-"
            "disturbance case (README: 'a disturbance injected into a ring "
            "at the sample clock's own rate is the worst possible "
            "disturbance'). Routed chip pin -> digital -> combiner_sampler, "
            "never chip pin -> combiner_sampler directly: the composed row "
            "is ring1 | ring2 | combiner_sampler | digital, so entering at "
            "digital and fanning out into the adjacent combiner_sampler "
            "region crosses only the digital|combiner_sampler channel, "
            "never a ring's own channel -- the routing topology this "
            "README's DR-0012 discussion already requires ('clk reaches the "
            "samplers from the digital side without crossing either ring's "
            "guarded area') must not be undone by phase 2. `digital`'s own "
            "real, routed `clk` pin lands on Metal4 (`layout/digital/"
            "trng_top.def`'s `PINS` section, `+ LAYER Metal4`) -- several "
            "levels above where ring1/ring2/combiner_sampler's own content "
            "lives, so reaching it needs a hand-drawn Metal4-to-lower-metal "
            "via-stack transition (`klt gen-compose`'s own gf180mcu routing-"
            "role map has no `metal4`/`via3` role as of `klt 0.4.0+"
            "g3fbb4478e301` -- klayout-tools#1670). Deferred to phase 2, "
            "flagged here so it is not rediscovered."
        ),
    },
    {
        "name": "rst_n",
        "role": "reset",
        "chip_pin": True,
        "endpoints": [("digital", "rst_n"), ("combiner_sampler", "rst_n")],
        "layer_role": "metal4_transition",
        "rationale": (
            "Same topology as `clk` (chip pin -> digital -> combiner_"
            "sampler, never crossing a ring's own channel) and the same "
            "Metal4-transition need -- a deterministic aggressor, same "
            "placement constraint as the sample clock."
        ),
    },
    {
        "name": "raw_bit",
        "role": "raw_tap",
        "chip_pin": False,
        "endpoints": [("combiner_sampler", "raw_bit"), ("digital", "raw_bit")],
        "layer_role": "metal4_transition",
        "rationale": (
            "Raw (pre-conditioning) sampled bit, combiner_sampler -> "
            "digital -- a single adjacent-channel hop, but still needs the "
            "same Metal4 transition `clk`/`rst_n` need, on the digital side."
        ),
    },
    {
        "name": "raw_valid",
        "role": "raw_tap",
        "chip_pin": False,
        "endpoints": [("combiner_sampler", "raw_valid"), ("digital", "raw_valid")],
        "layer_role": "metal4_transition",
        "rationale": "Raw-bit valid strobe, combiner_sampler -> digital, same as raw_bit.",
    },
    {
        "name": "ring_bit1",
        "role": "liveness_tap",
        "chip_pin": False,
        "endpoints": [
            ("combiner_sampler", "ring_bit1"),
            ("digital", "ring_bit[0]"),
        ],
        "layer_role": "metal4_transition",
        "rationale": (
            "DR-0016 per-ring liveness digitizer, ring1's own tap, "
            "combiner_sampler -> digital. The two committed reference "
            "netlists name this net differently (`ring_bit1` in "
            "combiner_sampler.spice, `ring_bit[0]` in trng_top.lvs_"
            "reference.spice) -- resolved here, in the declared "
            "connectivity, rather than by silently renaming either "
            "committed reference."
        ),
    },
    {
        "name": "ring_bit2",
        "role": "liveness_tap",
        "chip_pin": False,
        "endpoints": [
            ("combiner_sampler", "ring_bit2"),
            ("digital", "ring_bit[1]"),
        ],
        "layer_role": "metal4_transition",
        "rationale": (
            "DR-0016 per-ring liveness digitizer, ring2's own tap -- same "
            "name-mismatch resolution as ring_bit1."
        ),
    },
    # -------------------------------------------------------------------- #
    # The four supply branches. DO NOT MERGE THESE FOUR NETS -- see the
    # module docstring's "The four supply branches must never merge before
    # a star point" section. Each must keep its own distinct `name` and a
    # single-region `endpoints` list; `validate_inter_region_nets()` asserts
    # this mechanically on every run.
    # -------------------------------------------------------------------- #
    {
        "name": "vddr1",
        "role": "supply",
        "chip_pin": True,
        "endpoints": [("ring1", "vddr")],
        "layer_role": "metal2",
        "rationale": (
            "ring1's own star branch (Mechanism 2, item 1): chip pin "
            "straight to ring1's own `vddr` pin, on Metal2 (the supply-rail "
            "convention `layout/rings/ro_ring11/build.py` already "
            "documents for crossing Metal1 signal chains without a same-"
            "layer short) -- must never share a strap segment with vddr2/"
            "vdd/vddd before a not-yet-drawn star point."
        ),
    },
    {
        "name": "vddr2",
        "role": "supply",
        "chip_pin": True,
        "endpoints": [("ring2", "vddr")],
        "layer_role": "metal2",
        "rationale": "ring2's own star branch -- same constraint as vddr1.",
    },
    {
        "name": "vdd",
        "role": "supply",
        "chip_pin": True,
        "endpoints": [("combiner_sampler", "vdd")],
        "layer_role": "metal2",
        "rationale": (
            "combiner_sampler's own star branch -- also feeds the two DR-"
            "0018 `ro_buf` instances already inside combiner_sampler "
            "(`xb1`/`xb2`, run off the block supply deliberately, never off "
            "either ring's own `vddr1`/`vddr2`)."
        ),
    },
    {
        "name": "vddd",
        "role": "supply",
        "chip_pin": True,
        "endpoints": [],
        "implicit_regions": [("digital", "vddd")],
        "layer_role": "metal4_5_pdn_transition",
        "rationale": (
            "digital's own star branch. Not an `endpoints` entry: digital's "
            "committed reference `.SUBCKT trng_top` does not declare a "
            "`vddd` pin at all (see the module docstring's 'digital region's "
            "supply pins are not .SUBCKT pins' section) -- this connection "
            "is real in the actual layout (`layout/digital/README.md#power`'s "
            "own `SPECIALNETS`/PDN grid, Metal1 followpins + Metal4/Metal5 "
            "straps) but not expressible against the current reference "
            "netlist's own pin list."
        ),
    },
    {
        "name": "vss",
        "role": "ground",
        "chip_pin": True,
        "endpoints": [
            ("ring1", "vss"),
            ("ring2", "vss"),
            ("combiner_sampler", "vss"),
        ],
        "implicit_regions": [("digital", "vss")],
        "layer_role": "metal2_plus_digital_pdn_transition",
        "rationale": (
            "The one deliberately shared net (Mechanism 2): every region's "
            "own guard ring taps to its own `vss` return, and all four "
            "regions' returns converge at one point. ring1/ring2/combiner_"
            "sampler each declare a real `vss` pin; digital's does not (same "
            "implicit-SPECIALNETS reason as vddd) -- the wiring `digital` "
            "side is documented, not mechanically checked."
        ),
    },
    {
        "name": "vsubs",
        "role": "substrate",
        "chip_pin": False,
        "endpoints": [
            ("ring1", "vsubs"),
            ("ring2", "vsubs"),
            ("combiner_sampler", "vsubs"),
        ],
        "layer_role": "guard_ring_tap",
        "rationale": (
            "Not in issue #221's own inter-region table -- design/"
            "trng_top.spice's schematic has no `vsubs` pin; it exists only "
            "in ring1/ring2/combiner_sampler's own hand-derived layout LVS "
            "reference netlists, standing in for the extraction deck's own "
            "synthesized substrate handle (see the module docstring). "
            "Declared as its own net, not merged into `vss`, purely so the "
            "composed reference below can wire a complete X-card for these "
            "three regions -- no metal route is implied; physically this is "
            "the guard rings' own p-substrate taps (`add_well: False`), not "
            "a drawn wire."
        ),
    },
]


# --------------------------------------------------------------------------- #
# Reading a region's own committed reference pin list
# --------------------------------------------------------------------------- #

_SUBCKT_HEADER_RE = re.compile(r"^\.subckt\s+(\S+)\s+(.*)$", re.MULTILINE | re.IGNORECASE)


def _join_spice_continuations(text: str) -> str:
    """Fold every SPICE `+`-prefixed continuation line into its predecessor
    -- the same small helper `layout/floorplan/floorplan.py`'s own
    `_reference_top_pins` and `layout/digital/lvs.py`'s own `_library_cell_
    pins` each keep a private copy of, for the same reason: it only ever
    reads a header a reference file already carries, never builds one.
    """
    joined: list[str] = []
    for line in text.split("\n"):
        if line.startswith("+") and joined:
            joined[-1] = f"{joined[-1]} {line[1:].strip()}"
        else:
            joined.append(line)
    return "\n".join(joined)


def reference_top_pins(path: Path, top: str) -> list[str]:
    """The declared pin list off `path`'s own `.SUBCKT <top> ...` header."""
    if not path.is_file():
        raise FloorplanNetlistError(
            f"{path.relative_to(REPO_ROOT)} does not exist -- cannot read its "
            f"`.SUBCKT {top}` pin list"
        )
    text = _join_spice_continuations(path.read_text(errors="replace"))
    for name, pins in _SUBCKT_HEADER_RE.findall(text):
        if name.lower() == top.lower():
            return pins.split()
    raise FloorplanNetlistError(
        f"{path.relative_to(REPO_ROOT)} has no `.SUBCKT {top}` header -- "
        "cannot derive its declared pin list"
    )


# --------------------------------------------------------------------------- #
# Self-check -- issue #221's own acceptance criterion: verify every declared
# endpoint against the real, committed reference files, mechanically.
# --------------------------------------------------------------------------- #


def validate_inter_region_nets() -> list[str]:
    """Return a list of human-readable problems; empty means the declared
    net list is internally consistent with the four regions' own committed
    reference `.spice` files. Needs no `klt`, no PDK -- everything here is a
    plain-text read of files already committed to this repository.
    """
    problems: list[str] = []

    pins_by_region: dict[str, list[str]] = {}
    for rid, (path, top) in REGION_REFERENCES.items():
        try:
            pins_by_region[rid] = reference_top_pins(path, top)
        except FloorplanNetlistError as exc:
            problems.append(str(exc))
            pins_by_region[rid] = []

    seen_names: set[str] = set()
    claimed_pins: dict[tuple[str, str], str] = {}  # (region, pin) -> net name

    for net in INTER_REGION_NETS:
        name = net["name"]
        if name in seen_names:
            problems.append(f"net {name!r} is declared more than once")
        seen_names.add(name)

        for rid, pin in net.get("endpoints", ()):
            if rid not in REGION_REFERENCES:
                problems.append(
                    f"net {name!r} names unknown region {rid!r} (not in "
                    "REGION_REFERENCES)"
                )
                continue
            if pin not in pins_by_region[rid]:
                problems.append(
                    f"net {name!r} claims region {rid!r} pin {pin!r}, but "
                    f"{REGION_REFERENCES[rid][0].relative_to(REPO_ROOT)}'s own "
                    f"`.SUBCKT {REGION_REFERENCES[rid][1]}` header does not "
                    f"declare that pin (has: {pins_by_region[rid]})"
                )
                continue
            prior = claimed_pins.get((rid, pin))
            if prior is not None and prior != name:
                problems.append(
                    f"region {rid!r} pin {pin!r} is claimed by two different "
                    f"nets ({prior!r} and {name!r})"
                )
            claimed_pins[(rid, pin)] = name

        for rid, specialnet in net.get("implicit_regions", ()):
            if rid != "digital":
                problems.append(
                    f"net {name!r} declares an `implicit_regions` entry for "
                    f"region {rid!r} -- only 'digital' has undeclared "
                    "SPECIALNETS-only supply pins (see DIGITAL_IMPLICIT_"
                    "SPECIALNETS's own docstring)"
                )
            if specialnet not in DIGITAL_IMPLICIT_SPECIALNETS:
                problems.append(
                    f"net {name!r} declares an `implicit_regions` entry "
                    f"naming {specialnet!r}, which is not one of "
                    f"DIGITAL_IMPLICIT_SPECIALNETS {DIGITAL_IMPLICIT_SPECIALNETS}"
                )
            if specialnet != name:
                problems.append(
                    f"net {name!r}'s own `implicit_regions` entry names "
                    f"specialnet {specialnet!r}, which does not match this "
                    "net's own name -- an implicit connection should always "
                    "be declared under the net it is a connection *of*"
                )

        for rid in net.get("spans_regions", ()):
            if rid not in REGION_REFERENCES:
                problems.append(
                    f"net {name!r}'s `spans_regions` names unknown region "
                    f"{rid!r}"
                )

    # -- Every ring1/ring2/combiner_sampler pin must be claimed by exactly
    # one net: these three regions' own `.SUBCKT` headers are short and
    # fully analog/inter-region by construction (see the module docstring),
    # so an unclaimed pin here means either this table or that region's own
    # committed reference has drifted and nobody has reconciled them yet.
    for rid in ("ring1", "ring2", "combiner_sampler"):
        unclaimed = [
            pin for pin in pins_by_region.get(rid, ()) if (rid, pin) not in claimed_pins
        ]
        if unclaimed:
            problems.append(
                f"region {rid!r}'s own committed reference declares "
                f"pin(s) {unclaimed} that no INTER_REGION_NETS entry claims"
            )

    # -- The star-point separation invariant (module docstring): vddr1,
    # vddr2, vdd, vddd must be four distinct nets with disjoint endpoint
    # regions, so a future edit cannot silently merge two of them.
    supply_nets = [net for net in INTER_REGION_NETS if net["role"] == "supply"]
    supply_names = [net["name"] for net in supply_nets]
    if sorted(supply_names) != ["vdd", "vddd", "vddr1", "vddr2"]:
        problems.append(
            "expected exactly the four supply nets {vdd, vddd, vddr1, "
            f"vddr2}}, found {sorted(supply_names)}"
        )
    supply_regions: dict[str, str] = {}
    for net in supply_nets:
        regions = {rid for rid, _ in net.get("endpoints", ())}
        regions |= {rid for rid, _ in net.get("implicit_regions", ())}
        for rid in regions:
            prior = supply_regions.get(rid)
            if prior is not None and prior != net["name"]:
                problems.append(
                    f"region {rid!r} is reached by two different supply "
                    f"nets ({prior!r} and {net['name']!r}) -- the four "
                    "supply branches must stay separate to their own star "
                    "point"
                )
            supply_regions[rid] = net["name"]

    # -- ro1's long-haul flag (module docstring / issue #221 acceptance
    # criterion) must survive.
    ro1 = next((net for net in INTER_REGION_NETS if net["name"] == "ro1"), None)
    if ro1 is None:
        problems.append("net 'ro1' (ring1.ro -> combiner_sampler.rn1) is missing")
    elif ro1.get("spans_regions") != ["ring2"]:
        problems.append(
            "net 'ro1' must declare spans_regions == ['ring2'] (the long-"
            f"haul route around ring2's own guarded region); found "
            f"{ro1.get('spans_regions')!r}"
        )

    return problems


# --------------------------------------------------------------------------- #
# The LVS-reference generator
# --------------------------------------------------------------------------- #


def _endpoint_map() -> dict[tuple[str, str], str]:
    """`(region_id, region_pin_name) -> composed top-level net name`, for
    every declared, mechanically-checkable endpoint."""
    mapping: dict[tuple[str, str], str] = {}
    for net in INTER_REGION_NETS:
        for rid, pin in net.get("endpoints", ()):
            mapping[(rid, pin)] = net["name"]
    return mapping


def _wired_pins(rid: str, mapping: dict[tuple[str, str], str]) -> list[str]:
    """The net name wired to each of `rid`'s own pins, in that region's own
    committed pin order -- an unmapped pin passes through under its own
    name (only `digital` has any: its 105 chip-only pins)."""
    path, top = REGION_REFERENCES[rid]
    return [mapping.get((rid, pin), pin) for pin in reference_top_pins(path, top)]


def _external_pins() -> list[str]:
    """Every `trng_floorplan`-level chip pin: each `chip_pin: True` net's
    own name, plus every region pin that passes through unmapped (`digital`
    only). Sorted the same plain-string way `layout/digital/lvs.py`'s own
    `_top_pins` sorts `trng_top`'s header, so the two headers agree on
    convention even though this one is smaller.
    """
    mapping = _endpoint_map()
    external: set[str] = {net["name"] for net in INTER_REGION_NETS if net["chip_pin"]}
    mapped_pins = set(mapping)
    for rid in REGION_REFERENCES:
        path, top = REGION_REFERENCES[rid]
        for pin in reference_top_pins(path, top):
            if (rid, pin) not in mapped_pins:
                external.add(pin)
    return sorted(external)


def generate_lvs_reference() -> str:
    """Build `trng_floorplan.lvs_reference.spice`'s own text (does not write
    it -- see `write_lvs_reference`). Raises `FloorplanNetlistError` if
    `validate_inter_region_nets()` finds a problem; a composed reference
    built over a broken declaration would just be a second, differently-
    broken artefact.
    """
    problems = validate_inter_region_nets()
    if problems:
        raise FloorplanNetlistError(
            "cannot generate the composed LVS reference: "
            + "; ".join(problems)
        )

    mapping = _endpoint_map()
    external_pins = _external_pins()

    lines = [
        "* trng_floorplan -- LVS reference (composed) netlist.",
        "*",
        "* Generated by design/floorplan_netlist.py -- do not hand-edit.",
        "* Phase 1 of issue #219's own two-phase decomposition (issue #221):",
        "* this file wires the four regions' own already-committed reference",
        "* subcircuits together per INTER_REGION_NETS, declared as reviewable",
        "* Python data in that module. It does NOT correspond to any drawn",
        "* geometry yet -- the physical routing, the klt extract --top",
        "* trng_floorplan pin-count change, and running klt lvs against this",
        "* file are phase 2's work (a separate, follow-up issue), not done here.",
        "*",
        "* vddd is written as a top-level pin below with no wire beneath it:",
        "* digital's own committed reference (layout/digital/trng_top.lvs_",
        "* reference.spice) does not declare a vddd .SUBCKT pin (SPECIALNETS-",
        "* only -- see design/floorplan_netlist.py's own module docstring).",
        "* vss is wired to ring1/ring2/combiner_sampler only for the same",
        "* reason; digital's own vss return is real but not expressible here.",
        "*",
        "* Each region's own reference is pulled in by .INCLUDE rather than",
        "* copied a second time (digital's own reference alone is ~8700",
        "* lines) -- paths below are relative to this file's own directory.",
    ]

    for rid in REGION_ORDER:
        path, _top = REGION_REFERENCES[rid]
        rel = os.path.relpath(path, LVS_REFERENCE_PATH.parent)
        lines.append(f".INCLUDE {rel}")
    lines.append("")

    lines.append(f".SUBCKT {TOP_CELL} " + " ".join(external_pins))
    for rid in REGION_ORDER:
        _path, top = REGION_REFERENCES[rid]
        nets = _wired_pins(rid, mapping)
        lines.append(f"X_{rid.upper()} " + " ".join(nets) + f" {top}")
    lines.append(f".ENDS {TOP_CELL}")
    lines.append("")

    return "\n".join(lines) + "\n"


def write_lvs_reference() -> Path:
    text = generate_lvs_reference()
    LVS_REFERENCE_PATH.write_text(text)
    return LVS_REFERENCE_PATH


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="floorplan_netlist.py",
        description=(
            "Declare the trng_floorplan inter-region net list and self-"
            "check it against the four regions' own committed reference "
            "netlists (issue #221)."
        ),
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="also (re)write layout/floorplan/trng_floorplan.lvs_reference.spice",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="self-check only (the default with no flags)",
    )
    args = parser.parse_args(argv)

    problems = validate_inter_region_nets()
    print(f"inter-region nets declared: {len(INTER_REGION_NETS)}")
    if problems:
        print(f"FAIL: {len(problems)} problem(s):")
        for problem in problems:
            print(f"  - {problem}")
        return EXIT_FAIL
    print("PASS: every declared endpoint names a real pin on its region's "
          "own committed reference netlist.")

    if args.write:
        path = write_lvs_reference()
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    elif not args.check:
        # No flags at all: still report whether the committed file matches
        # what this declaration would generate, without writing anything.
        generated = generate_lvs_reference()
        if not LVS_REFERENCE_PATH.is_file():
            print(
                f"NOTE: {LVS_REFERENCE_PATH.relative_to(REPO_ROOT)} does not "
                "exist yet -- re-run with --write to create it"
            )
        elif LVS_REFERENCE_PATH.read_text() != generated:
            print(
                f"NOTE: {LVS_REFERENCE_PATH.relative_to(REPO_ROOT)} does not "
                "match this declaration -- re-run with --write to refresh it"
            )
        else:
            print(f"ok    {LVS_REFERENCE_PATH.relative_to(REPO_ROOT)} matches "
                  "this declaration")

    return EXIT_OK


if __name__ == "__main__":
    raise SystemExit(main())
