#!/usr/bin/env python3
"""Deterministic SPICE export of the xschem schematics in ``design/xschem/``.

    python3 design/netlist.py            # (re-)export every top cell
    python3 design/netlist.py --check    # export to a temp dir and diff; never writes

``--check`` is the staleness guard: it fails if the committed ``.spice``
netlist does not match what the current schematics produce. That is what
makes a committed netlist evidence rather than a snapshot someone forgot to
refresh -- ``sim/README.md`` records a ``netlist.sha`` in every evidence
record, and that SHA is only meaningful if the netlist provably comes from
the schematic it claims to.

Determinism
-----------
xschem writes absolute filesystem paths into the netlist header comments
(``** sch_path:``/``** sym_path:``) and resolves the PDK symbol library
through an rc file. Both are machine-specific, so this script:

* generates the xschem rc file itself, resolving the gf180mcu PDK through
  the same chain ``sim/harness/pdk.py`` uses (``GF180_PDK_PATH`` /
  ``PDK_ROOT`` + ``PDK`` / ``sim/pdk.local.json`` / ``sim/pdk.json`` /
  built-in search roots), so nothing here hardcodes a path; and
* rewrites every absolute path in the output to a repo-relative one.

The result is byte-identical on any machine with the same xschem version
and PDK symbol set. The xschem version is *not* pinned by this script; if a
future xschem changes its netlist formatting, ``--check`` will say so
loudly rather than letting the two drift apart silently.
"""

from __future__ import annotations

import argparse
import difflib
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DESIGN_DIR = REPO_ROOT / "design"
SCHEMATIC_DIR = DESIGN_DIR / "xschem"

#: Schematics exported as stand-alone netlists. Cells not listed here are
#: still netlisted, but only as subcircuits inside a top cell that uses them.
TOP_CELLS = ("ro_array_core", "ro_array_sanity")

XSCHEM = "xschem"

EXIT_OK = 0
EXIT_STALE = 1
EXIT_ENVIRONMENT = 3


class ExportError(RuntimeError):
    pass


def _pdk_symbol_dir() -> Path:
    """The gf180mcu xschem symbol library, resolved like the sim harness does."""
    sys.path.insert(0, str(REPO_ROOT / "sim"))
    try:
        from harness.pdk import PdkNotFound, find_pdk  # noqa: PLC0415
    except ImportError as exc:  # pragma: no cover - repo layout is fixed
        raise ExportError(f"cannot import the sim harness PDK resolver: {exc}") from exc
    try:
        pdk = find_pdk()
    except PdkNotFound as exc:
        raise ExportError(str(exc)) from exc
    symbols = pdk.path / "libs.tech" / "xschem" / "symbols"
    if not symbols.is_dir():
        raise ExportError(
            f"{pdk.path} has no libs.tech/xschem/symbols directory -- this PDK "
            "install does not carry the xschem symbol library"
        )
    return symbols


def _write_rcfile(target: Path, symbol_dir: Path, netlist_dir: Path) -> None:
    target.write_text(
        "# generated by design/netlist.py -- do not edit, do not commit\n"
        "set XSCHEM_LIBRARY_PATH {}\n"
        "append XSCHEM_LIBRARY_PATH :${XSCHEM_SHAREDIR}/xschem_library/devices\n"
        f"append XSCHEM_LIBRARY_PATH :{symbol_dir}\n"
        f"append XSCHEM_LIBRARY_PATH :{SCHEMATIC_DIR}\n"
        f"set netlist_dir {netlist_dir}\n"
        "set netlist_type spice\n"
        "set hspice_netlist 0\n"
    )


def _normalize(text: str) -> str:
    """Make the netlist machine-independent and stable line-for-line."""
    out = []
    for line in text.splitlines():
        # xschem stamps absolute paths into header comments.
        line = re.sub(r"(?<=[ :])/[^\s]*/(?=[^/\s]+\.(?:sch|sym))", "", line)
        line = line.replace(str(REPO_ROOT) + "/", "")
        # The export is a library of subcircuits that a testbench deck
        # `.include`s, not a deck of its own: a bare `.end` would truncate
        # every deck that includes it. `.ends` is kept, obviously.
        if line.strip().lower() == ".end":
            continue
        # xschem comments out the TOP cell's own .subckt/.ends wrapper,
        # because from its point of view the top schematic is a deck rather
        # than a cell. Here the top cell is exactly what a testbench wants
        # to instantiate, so the wrapper is restored. Every lower-level cell
        # is already emitted uncommented and is untouched by this.
        if line.startswith("**.subckt ") or line.strip() == "**.ends":
            line = line[2:]
        out.append(line.rstrip())
    while out and not out[-1]:
        out.pop()
    return "\n".join(out) + "\n"


def export(top: str, outdir: Path) -> str:
    if shutil.which(XSCHEM) is None:
        raise ExportError(
            "xschem not found on PATH.\n"
            "  Debian/Ubuntu: apt-get install xschem\n"
            "  or build from https://github.com/StefanSchippers/xschem"
        )
    schematic = SCHEMATIC_DIR / f"{top}.sch"
    if not schematic.is_file():
        raise ExportError(f"no schematic {schematic}")
    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        rcfile = tmpdir / "xschemrc"
        _write_rcfile(rcfile, _pdk_symbol_dir(), tmpdir)
        env = dict(os.environ)
        env.pop("XSCHEM_LIBRARY_PATH", None)
        proc = subprocess.run(
            [
                XSCHEM, "-n", "-q", "-x", "-s", "-r",
                "--rcfile", str(rcfile),
                "-o", str(tmpdir),
                "-N", f"{top}.spice",
                str(schematic),
            ],
            capture_output=True,
            text=True,
            cwd=tmpdir,
            env=env,
            check=False,
        )
        produced = tmpdir / f"{top}.spice"
        if not produced.is_file():
            raise ExportError(
                f"xschem produced no netlist for {top}\n"
                f"--- stdout ---\n{proc.stdout}\n--- stderr ---\n{proc.stderr}"
            )
        text = _normalize(produced.read_text())
    header = (
        f"* {top} -- GENERATED by design/netlist.py from design/xschem/{top}.sch\n"
        "* Do not edit by hand: `python3 design/netlist.py --check` fails if this\n"
        "* file and the schematic disagree. Regenerate with `python3 design/netlist.py`.\n"
    )
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / f"{top}.spice").write_text(header + text)
    return header + text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="netlist.py",
        description="Export (or verify) the SPICE netlists of design/xschem/.",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="do not write: re-export and fail if the committed netlist is stale",
    )
    parser.add_argument("--top", action="append", metavar="CELL", help="cell to export (repeatable)")
    args = parser.parse_args(argv)

    tops = tuple(args.top) if args.top else TOP_CELLS
    status = EXIT_OK
    for top in tops:
        committed = DESIGN_DIR / f"{top}.spice"
        try:
            if args.check:
                with tempfile.TemporaryDirectory() as tmp:
                    fresh = export(top, Path(tmp))
                if not committed.is_file():
                    print(f"STALE  {top}: {committed.relative_to(REPO_ROOT)} does not exist")
                    status = EXIT_STALE
                    continue
                current = committed.read_text()
                if current != fresh:
                    diff = difflib.unified_diff(
                        current.splitlines(True), fresh.splitlines(True),
                        fromfile=f"committed/{top}.spice", tofile=f"regenerated/{top}.spice",
                    )
                    print(f"STALE  {top}: committed netlist does not match the schematic")
                    sys.stdout.writelines(diff)
                    status = EXIT_STALE
                else:
                    print(f"ok     {top}: committed netlist matches design/xschem/{top}.sch")
            else:
                export(top, DESIGN_DIR)
                print(f"wrote  design/{top}.spice")
        except ExportError as exc:
            print(f"ERROR  {top}: {exc}", file=sys.stderr)
            return EXIT_ENVIRONMENT
    return status


if __name__ == "__main__":
    raise SystemExit(main())
