"""Deck composition and ngspice execution for one PVT point (one or more
seeded runs, for stochastic testbenches)."""

from __future__ import annotations

import re
import shutil
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path

from .corners import PvtPoint
from .pdk import Pdk
from .testbench import Testbench

NGSPICE = "ngspice"
DEFAULT_TIMEOUT_S = 300

# `print` output for a length-1 vector: "m_vout = 6.9043645202e-01"
_MEAS_RE = re.compile(r"^\s*m_(\w+)\s*=\s*([-+]?[0-9.]+(?:[eE][-+]?[0-9]+)?)\s*$")
_ERROR_RE = re.compile(r"^\s*(?:Error|ERROR|Fatal|fatal error|doAnalyses:)", re.MULTILINE)


class NgspiceMissing(RuntimeError):
    pass


def ngspice_version() -> str:
    exe = shutil.which(NGSPICE)
    if not exe:
        raise NgspiceMissing(
            "ngspice not found on PATH.\n"
            "  macOS:  brew install ngspice\n"
            "  Debian: apt-get install ngspice"
        )
    out = subprocess.run(
        [exe, "--version"], capture_output=True, text=True, check=False
    ).stdout
    for line in out.splitlines():
        if "ngspice-" in line:
            return line.strip().lstrip("* ").strip()
    return out.strip().splitlines()[0] if out.strip() else "unknown"


def compose_deck(tb: Testbench, pdk: Pdk, point: PvtPoint, seed: int | None = None) -> str:
    """Build the complete, self-contained ngspice deck for one PVT point.

    ``seed`` -- when given -- is emitted as ``.option seed=<seed>`` ahead of
    the model include, so it governs every random draw in the run (device
    mismatch, ``trnoise()`` sources, Monte Carlo skew). Required by the
    harness for any testbench whose ``analysis_type`` is stochastic.
    """
    lines: list[str] = [
        f"* {tb.slug} @ {point.corner_id} -- GENERATED by sim/harness, do not edit",
        f"* corner={point.corner.name} ({point.corner.description})",
        f"* temp={point.temp_c} C  vdd={point.vdd} V  pdk={pdk.variant}@{pdk.version}",
        "",
        "* ---- PVT parameters -------------------------------------------------",
        f".param vdd_nom={tb.nominal_supply_v!r}",
        f".param vdd_val={point.vdd!r}",
        f".param temp_c={point.temp_c!r}",
    ]
    for key, value in tb.params.items():
        lines.append(f".param {key}={value}")

    lines += [
        "",
        "* ---- gf180mcu models ------------------------------------------------",
        f'.include "{pdk.design_include}"',
    ]
    if seed is not None:
        lines.append(f".option seed={seed}")
    # Design-switch overrides (e.g. sw_stat_mismatch=1) must come AFTER the
    # design.ngspice include above, or its own defaults win instead.
    for key, value in tb.design_params.items():
        lines.append(f".param {key}={value}")
    if tb.extra_lib_sections:
        # A section like "statistical" is a self-contained, mismatch-enabled
        # replacement for the plain per-family corner sections (it redefines
        # the same subckts with extra mismatch params) -- ngspice silently
        # *ignores* a second definition of the same subckt, so loading both
        # would leave the mismatch-enabled model shadowed by the plain one.
        # tb.json's "corners" still selects the PVT grid's process-corner
        # axis for bookkeeping (the record's corner.process field); only the
        # library sections actually `.lib`-included are overridden here.
        for section in tb.extra_lib_sections:
            lines.append(f'.lib "{pdk.model_lib}" {section}')
    else:
        for section in point.corner.sections:
            lines.append(f'.lib "{pdk.model_lib}" {section}')

    lines += [
        "",
        f".temp {point.temp_c!r}",
    ]
    for option in tb.options:
        lines.append(f".options {option}")

    lines += [
        "",
        "* ---- testbench ------------------------------------------------------",
        f'.include "{tb.netlist}"',
        "",
        "* ---- measurement ----------------------------------------------------",
        ".control",
        "set numdgt=10",
        "set noaskquit",
    ]
    lines += [f"  {analysis}" for analysis in tb.analyses]
    for name, expr in tb.measure.items():
        lines.append(f"  let m_{name} = {expr}")
    for name in tb.measure:
        lines.append(f"  print m_{name}")
    lines += [".endc", ".end", ""]
    return "\n".join(lines)


@dataclass
class RunResult:
    """The outcome of one seeded ngspice invocation at one PVT point."""

    point: PvtPoint
    seed: int | None
    status: str                                   # "ok" | "failed" | "error"
    measurements: dict[str, float] = field(default_factory=dict)
    missing: list[str] = field(default_factory=list)
    seconds: float = 0.0
    deck_name: str = ""
    log_name: str = ""
    message: str = ""


def parse_measurements(text: str) -> dict[str, float]:
    found: dict[str, float] = {}
    for line in text.splitlines():
        match = _MEAS_RE.match(line)
        if match:
            try:
                found[match.group(1)] = float(match.group(2))
            except ValueError:  # pragma: no cover - regex already constrains this
                continue
    return found


def run_one(
    tb: Testbench,
    pdk: Pdk,
    point: PvtPoint,
    workdir: Path,
    seed: int | None = None,
    run_index: int = 0,
    timeout_s: int = DEFAULT_TIMEOUT_S,
) -> RunResult:
    """Simulate one (PVT point, seed) pair. Never raises for sim failure.

    ``workdir`` holds both the generated deck and the raw ngspice log --
    it is the eventual ``sim/records/raw/<record-stem>/`` directory (or a
    scratch directory for a ``--no-write`` run).
    """
    workdir.mkdir(parents=True, exist_ok=True)
    stem = f"{point.corner_id}-run{run_index}" if seed is not None else point.corner_id
    deck_path = workdir / f"{stem}.spice"
    log_path = workdir / f"{stem}.log"
    deck_path.write_text(compose_deck(tb, pdk, point, seed=seed))

    started = time.monotonic()
    try:
        proc = subprocess.run(
            [NGSPICE, "-b", str(deck_path)],
            capture_output=True,
            text=True,
            timeout=timeout_s,
            cwd=workdir,
            check=False,
        )
        output = proc.stdout + "\n" + proc.stderr
        returncode = proc.returncode
    except FileNotFoundError as exc:
        raise NgspiceMissing(str(exc)) from exc
    except subprocess.TimeoutExpired:
        elapsed = time.monotonic() - started
        log_path.write_text(f"TIMEOUT after {timeout_s}s\n")
        return RunResult(
            point=point,
            seed=seed,
            status="error",
            seconds=elapsed,
            deck_name=deck_path.name,
            log_name=log_path.name,
            message=f"ngspice timed out after {timeout_s}s",
        )
    elapsed = time.monotonic() - started
    log_path.write_text(output)

    measurements = parse_measurements(output)
    missing = [name for name in tb.measure if name not in measurements]

    if missing:
        errors = "; ".join(_ERROR_RE.findall(output)[:3])
        first_error = next(
            (line.strip() for line in output.splitlines() if _ERROR_RE.match(line)), ""
        )
        return RunResult(
            point=point,
            seed=seed,
            status="failed",
            measurements=measurements,
            missing=missing,
            seconds=elapsed,
            deck_name=deck_path.name,
            log_name=log_path.name,
            message=first_error or errors or f"ngspice exit {returncode}, no measurements parsed",
        )

    return RunResult(
        point=point,
        seed=seed,
        status="ok",
        measurements=measurements,
        seconds=elapsed,
        deck_name=deck_path.name,
        log_name=log_path.name,
    )


def plan_runs(tb: Testbench, seeds: list[int] | None) -> list[tuple[int | None, int]]:
    """The ``(seed, run_index)`` pairs one PVT point needs.

    This is where the "no seed, no evidence" rule from ``sim/README.md`` is
    enforced, so that both the serial (:func:`run_point`) and the parallel
    (``run_corners.py -j``) execution paths inherit it from one place.
    """
    if not tb.stochastic:
        return [(None, 0)]
    if not seeds:
        raise ValueError(
            f"{tb.slug}: stochastic testbench (analysis_type={tb.analysis_type!r}) "
            "requires at least one seed -- sim/README.md: 'no seed, no evidence'"
        )
    return [(seed, i) for i, seed in enumerate(seeds)]


def run_point(
    tb: Testbench,
    pdk: Pdk,
    point: PvtPoint,
    workdir: Path,
    seeds: list[int] | None,
    timeout_s: int = DEFAULT_TIMEOUT_S,
) -> list[RunResult]:
    """Run every seed (or the single deterministic run) for one PVT point."""
    return [
        run_one(tb, pdk, point, workdir, seed=seed, run_index=index, timeout_s=timeout_s)
        for seed, index in plan_runs(tb, seeds)
    ]
